### ISSUE TITLE
handle absence of scopes

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#114] opened 2018-06-09 17:18 UTC
The JWT issued by API Keys do not have OAuth scopes. The adapter should handle the use case where an API Product has scopes, but is used with API Keys.

**Comment by theganyo** [comment] 2018-06-09 17:20
Duplicate of https://github.com/apigee/istio-mixer-adapter/issues/111

**Closed by theganyo** 2018-06-09 17:20 UTC
